In [6]:
import numpy as np

In [7]:
# Let's creat and Np array and get its shape
np_list = np.array([1,2,3,4,5])

# now lets get its lenght wich should be 5 columns and zero rows
print(np_list.shape)
# prints the data type of the list
print(np_list.dtype)

(5,)
int64


## Creating np arrays

In [8]:
# np.empty([shape]) will produce a random np array of thes shape
a = np.empty([3,3])
print(a)
print(a.shape)

print(np.empty([3,256,3]))

[[1.84724979e-316 6.91714571e-310 6.91714576e-310]
 [6.91712279e-310 6.91712279e-310 6.91712279e-310]
 [6.91712279e-310 6.91714580e-310 3.95252517e-322]]
(3, 3)
[[[ 1.91877508e-316  2.47379808e-091  2.44041296e-154]
  [ 1.00838745e+261  4.91347521e+252  5.02065932e+276]
  [ 2.63625795e-085  1.05724129e-301  1.45240665e-312]
  ...
  [ 1.06758000e+224  1.46924108e+195  9.06756708e+271]
  [ 3.03181639e+180  1.14199214e+243  9.05280210e+223]
  [ 4.91347540e+252  5.02065932e+276  6.01334637e-154]]

 [[ 9.07652262e+223  5.03931372e+223  3.67289404e+194]
  [ 4.44387685e+252  6.01433277e+175  1.46923002e+195]
  [ 7.22940565e+159  1.88892019e+219  4.63658219e+228]
  ...
  [ 9.77824555e+199  6.01334653e-154  6.01347002e-154]
  [ 1.69375270e+190  2.35569008e+251  1.14448622e+243]
  [ 6.01347002e-154  3.03182642e+180  7.35876461e+223]]

 [[ 4.82410896e+228  6.01346953e-154  6.01347002e-154]
  [ 2.19341581e-152  9.30537465e+199  7.10084082e+194]
  [ 1.27734658e-152  1.39806873e-152  3.44304535e-085

In [9]:
# Np zeros creates an ap array wof the specified dimensions filled with zeros
b = np.zeros([3,3])

print(b)

# np ones creates a matrix filled with jist ones

c = np.ones([3,3])
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Combining arrays

In [10]:
#  vertical stack, this is basically adding an exra row to the
# vstack takes a tuple

array_1 = np.array([1,2,3])

array_2 = np.array([4,5,6])


matrix = np.vstack((array_1,array_2))

print(matrix)
print(matrix.shape)
# Hstack adds onto a row, thing of adding features to a dataset

matrix2 = np.hstack((array_1,array_2))

print(matrix2)

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5 6]


## Two-Dimensional Indexing

In [13]:
# Indexing arrays takes the form of array[0,0] instead of the regular array[0][0]

print(matrix[0,0])

# To get all of the items in the first row, indexing will look like array[1,]

print(matrix[1,])

1
[4 5 6]


## Two-Dimensional Slicing

In [14]:
data = np.array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
# In order to get the target(y) values and separate this from the features (X) we need to do some slicing
# data[:, :-1] this gets all of the rows(the first : all) and gets all of the columns up to the last column
# data[:, -1] this is saying get all of the rows, but only the first column
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [22]:
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


## Array Reshaping

In [25]:
# Array reshaping is essential to how some algorithms expect data to come in in libraies such as sklearn

data = np.array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


In [28]:
# Let's reshape this into a 2 which will flip the array over on its access and make every element into its own array
print(data.reshape((data.shape[0],1)))

[[11]
 [22]
 [33]
 [44]
 [55]]


In [53]:
# let's combine this

data =np.array([[1,2,3,4],
      [5,6,7,8],
      [9,10,11,12]])

split = 2
X= data[:,:-1]
y = data[:,-1]
print(X)

# reshape the data
y = y.reshape((y.shape[0],1))
print(y)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[ 4]
 [ 8]
 [12]]


## Lets reshape a 2d array unto a 3 d array and show the results

In [58]:
# What this will do is reshape the array so that there will only be a single digit
# in every array for every original array


print(data.shape[0])
print(data.shape[1])

data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)
print(data)

3
4
(3, 4, 1)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


## Array Broadcasting

As a review, arrays of different sizes cant be used as handy in arithmetic
so for the smaller array we give it the same dimensions as the larger

In [62]:
a= np.array([[1,2,3],[4,5,6]])
b= np.array([1])
print(a+b)
c = np.array([2,3,4])
print(a+c)

[[2 3 4]
 [5 6 7]]
[[ 3  5  7]
 [ 6  8 10]]
