In [2]:
import numpy as np

In [3]:
# Let's creat and Np array and get its shape
np_list = np.array([1,2,3,4,5])

# now lets get its lenght wich should be 5 columns and zero rows
print(np_list.shape)
# prints the data type of the list
print(np_list.dtype)

(5,)
int64


## Creating np arrays

In [5]:
# np.empty([shape]) will produce a random np array of thes shape
a = np.empty([3,3])
print(a)
print(a.shape)

print(np.empty([3,256,3]))

[[2.15874277e-316 6.94716006e-310 6.94716010e-310]
 [6.94712916e-310 6.94712916e-310 6.94712916e-310]
 [6.94712916e-310 6.94716015e-310 3.95252517e-322]]
(3, 3)
[[[5.09205398e-317 5.39650909e-317 5.39250914e-317]
  [3.32653376e-111 4.39453125e-003 1.38494908e+219]
  [2.88000001e+002 1.36752682e-312 7.63404877e+149]
  ...
  [1.33360321e+241 2.74034536e-310 1.17500849e-308]
  [8.20436208e-304 3.20578743e-317 1.06559869e-255]
  [8.73990349e+245 2.49224026e-306 1.10892017e-296]]

 [[1.07070186e-296 7.02484160e-292 5.83328478e-302]
  [2.21808893e-301 4.22884902e-307 5.62950976e+014]
  [4.53799245e+217 8.73555210e+183 6.22649560e+228]
  ...
  [1.51755021e-110 6.01347002e-154 1.38496744e+219]
  [2.49979799e+262 1.06306420e+224 2.43894953e-154]
  [6.01347002e-154 3.15474901e+180 1.03156610e+113]]

 [[6.61175426e+265 6.20651817e+223 2.31594540e+251]
  [5.29672261e+180 1.06306398e+224 1.14504952e+243]
  [6.01347002e-154 7.13222113e-154 3.28096914e-085]
  ...
  [1.95322203e+227 6.63068430e+265 1.

In [18]:
# Np zeros creates an ap array wof the specified dimensions filled with zeros
b = np.zeros([3,3])

print(b)

# np ones creates a matrix filled with jist ones

c = np.ones([3,3])
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Combining arrays

In [11]:
#  vertical stack, this is basically adding an exra row to the
# vstack takes a tuple

array_1 = np.array([1,2,3])

array_2 = np.array([4,5,6])


matrix = np.vstack((array_1,array_2))

print(matrix)
print(matrix.shape)
# Hstack adds onto a row, thing of adding features to a dataset

matrix2 = np.hstack((array_1,array_2))

print(matrix2)

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5 6]


## Two-Dimensional Indexing