In [2]:
import numpy as np

In [3]:
# Let's creat and Np array and get its shape
np_list = np.array([1,2,3,4,5])

# now lets get its lenght wich should be 5 columns and zero rows
print(np_list.shape)
# prints the data type of the list
print(np_list.dtype)

(5,)
int64


## Creating np arrays

In [4]:
# np.empty([shape]) will produce a random np array of thes shape
a = np.empty([3,3])
print(a)
print(a.shape)

print(np.empty([3,256,3]))

[[2.42979666e-316 6.91310861e-310 6.91310866e-310]
 [6.91309760e-310 6.91309760e-310 6.91309760e-310]
 [6.91309760e-310 6.91310871e-310 3.95252517e-322]]
(3, 3)
[[[ 2.49965083e-316  9.52661951e-292  3.69602929e-309]
  [ 5.25185407e+170  2.45591948e+198  1.21906099e-152]
  [ 2.28896110e+243  4.52351123e+257  1.33856863e-152]
  ...
  [ 1.06079535e-153  2.13780332e+161  5.03128776e+180]
  [ 7.29143969e-130  1.05019719e-153  7.54516493e-095]
  [ 2.65053637e-129  2.70444787e-308  3.38460953e+125]]

 [[ 8.66639636e-307  0.00000000e+000  3.62604445e-217]
  [ 4.33931561e-313  5.83350288e-302  1.60562873e-296]
  [ 9.98240035e-110  4.55695127e-303  1.82960175e-307]
  ...
  [ 6.19062304e+223  1.67437932e+243  1.71010347e+214]
  [ 7.22762050e+159  2.04740487e+161  6.61175426e+265]
  [ 2.31554970e-152  1.67793284e+243  1.46922886e+195]]

 [[ 1.72965980e+156  3.92386677e+252  1.28014460e-152]
  [ 1.69593260e-152  1.46922886e+195  5.48607088e+241]
  [ 1.21697546e-152  6.47514828e+170  2.66061854e-260

In [5]:
# Np zeros creates an ap array wof the specified dimensions filled with zeros
b = np.zeros([3,3])

print(b)

# np ones creates a matrix filled with jist ones

c = np.ones([3,3])
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Combining arrays

In [6]:
#  vertical stack, this is basically adding an exra row to the
# vstack takes a tuple

array_1 = np.array([1,2,3])

array_2 = np.array([4,5,6])


matrix = np.vstack((array_1,array_2))

print(matrix)
print(matrix.shape)
# Hstack adds onto a row, thing of adding features to a dataset

matrix2 = np.hstack((array_1,array_2))

print(matrix2)

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5 6]


## Two-Dimensional Indexing

In [11]:
# Indexing arrays takes the form of array[0,0] instead of the regular array[0][0]

print(matrix[0,0])

# To get all of the items in the first row, indexing will look like array[1,]

print(matrix[1,])

1
[4 5 6]


## Two-Dimensional Slicing

In [14]:
data = np.array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
# In order to get the target(y) values and separate this from the features (X) we need to do some slicing
# data[:, :-1] this gets all of the rows(the first : all) and gets all of the columns up to the last column
# data[:, -1] this is saying get all of the rows, but only the first column
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [22]:
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


## Array Reshaping

In [25]:
# Array reshaping is essential to how some algorithms expect data to come in in libraies such as sklearn

data = np.array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


In [28]:
# Let's reshape this into a 2d which will flip the array over on its axis and make every element into its own array
print(data.reshape((data.shape[0],1)))

[[11]
 [22]
 [33]
 [44]
 [55]]


In [1]:
# let's combine this

data = np.array([[1,2,3,4],
      [5,6,7,8],
      [9,10,11,12]])

split = 2
X= data[:,:-1]
y = data[:,-1]
print(X)

# reshape the data
y = y.reshape((y.shape[0],1))
print(y)

NameError: name 'np' is not defined

## Lets reshape a 2d array unto a 3 d array and show the results

In [4]:
# What this will do is reshape the array so that there will only be a single digit
# in every array for every original array

print(data.shape)
print(data.shape[0])
print(data.shape[1])

data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)
print(data)

(3, 4, 1)
3
4
(3, 4, 1)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


## Array Broadcasting

As a review, arrays of different sizes cant be used as handy in arithmetic
so for the smaller array we give it the same dimensions as the larger

In [62]:
a= np.array([[1,2,3],[4,5,6]])
b= np.array([1])
print(a+b)
c = np.array([2,3,4])
print(a+c)

[[2 3 4]
 [5 6 7]]
[[ 3  5  7]
 [ 6  8 10]]
