In [1]:
import numpy


## Square matrices

A square matrix is where the number of columns and the number of rows are the same

${n \equiv m} $

$$ {A} = \begin{pmatrix} (a_{1,1},a_{1,2},a_{1,3})\\ (a_{2,1,},a_{2,2},a_{2,3}) \\ (a_{3,1},a_{3,2},a_{3,3})  \end{pmatrix}$$

Why this is important is that these are readily added or rotated( like for images in preprocessing)

## Symmetric matrices
The top right triangle and the bottom left triange are the same, this means that the matrix transpose is the same as the oririnal matrix

$$ {A} = \begin{pmatrix} (1 \ 2 \ 3 \ 4  \ 5)\\ (2 \ 1 \ 2 \ 3 \ 4)  \\ (3 \ 2 \ 1 \ 2 \ 3) \\ (4 \ 3 \ 2 \ 1 \ 2) \\ (5 \ 4 \ 3 \ 2 \ 1) \end{pmatrix}$$


$ A = A^T$

if you notice, the middle row has th e same value( but not always)

## Triangular matrices

A triangular matrix is a matrix where all of the values are in the upper right part of the trianlge or the lower left

In [3]:
# triangular matrices
from numpy import array
from numpy import tril # lower left
from numpy import triu # upper right

M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])

#lets print the lower left matrix
print(tril(M))

# now lets print the upper right
print(triu(M))

[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


## Diagnal matrices

For a diagonal matrix, all values outside of the main diagonal (top left to bottom right) are 0. On the main diagonal, all the values can be produced as a vector


In [8]:
from numpy import diag
M = array([
[1, 0, 0],
[0, 2, 0],
[0, 0, 3]])

# Lets extract the diagonal

diag_vector = diag(M)

print(diag_vector)
# And in the opposite direction lets make the vector back into a diagonal matrix

back_into_matrix = diag(diag_vector)

print(back_into_matrix)

[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
