## Vectors

A vector has the following notation
$$v=\begin{pmatrix} a \\b \end{pmatrix}$$

But can also be describe as the following

$$v=\begin{pmatrix} a & b \end{pmatrix}$$


Vectors represent either a row or column of data and are most commonly used to represent y values

Example:

$$v=\begin{pmatrix} 0.6 \\0.5 \end{pmatrix}$$

## Vector addition,subtraction and multiplication


### Scalar
Following the ruls for collumns and rows, all vectors can be deivded by a scalar value and rrturn another vector with elementwise operations being perfromed on each of the  elements in the vector

In [10]:
import numpy as np

vector = np.array([2,56,66])
scalar = 3

array([ 2, 56, 66])

In [11]:
print(vector + 3)

[ 5 59 69]


In [12]:
print(vector - 3)

[-1 53 63]


In [14]:
print(vector * 3)

[  6 168 198]


In [15]:
print(vector / 3)

[ 0.66666667 18.66666667 22.        ]


## Vector Dot Products (multiplication of vectors)

Dot products calculate the sum of vectors of the same length

and have the following notation with the following outcome and will product a scalar value
$$a=\begin{pmatrix} 1 \\ 2 \end{pmatrix}$$
$$b=\begin{pmatrix} 3 \\ 3 \end{pmatrix}$$


$$c=\begin{pmatrix} a \times b \end{pmatrix}$$

=


$$c=\begin{pmatrix} a_{1} \times b_{1} + a_{2}\times b_{2} \end{pmatrix}$$

In [17]:
a= np.array([1,2])
b = np.array([3,4])

c = a.dot(b)
c

11

## Vector Norms

