## Vectors

A vector has the following notation

$$v=\begin{pmatrix} a \\b \end{pmatrix}$$

But can also be describe as the following

$$v=\begin{pmatrix} a & b \end{pmatrix}$$


Vectors represent either a row or column of data and are most commonly used to represent y values

Example:

$$v=\begin{pmatrix} 0.6 \\0.5 \end{pmatrix}$$

## Vector addition,subtraction and multiplication


### Scalar
Following the rules for collumns and rows, all vectors can be deivded by a scalar value and rrturn another vector with elementwise operations being perfromed on each of the  elements in the vector

In [8]:
import numpy as np

vector = np.array([2,56,66])
scalar = 3

In [2]:
print(vector + 3)

[ 5 59 69]


In [3]:
print(vector - 3)

[-1 53 63]


In [4]:
print(vector * 3)

[  6 168 198]


In [5]:
print(vector / 3)

[ 0.66666667 18.66666667 22.        ]


## Vector Dot Products (multiplication of vectors)

Dot products calculate the sum of vectors of the same length

and have the following notation with the following outcome and will product a scalar value
$$a=\begin{pmatrix} 1 \\ 2 \end{pmatrix}$$
$$b=\begin{pmatrix} 3 \\ 3 \end{pmatrix}$$


$$c=\begin{pmatrix} a \times b \end{pmatrix}$$

=


$$c=\begin{pmatrix} a_{1} \times b_{1} + a_{2}\times b_{2} \end{pmatrix}$$

In [6]:
a= np.array([1,2])
b = np.array([3,4])

c = a.dot(b)
c

11

## Vector Norms
The length of a vector describes the extent of the vector in space, and is also reffered to as the magnitude or the norm

The length or magnitude of the vector is also called the vector norm

The three norms that we'll go over is:

$L^1$ Norm

$L^2$ Norm

Vector Max Norm




## $L^1$ Norm


AKA the Mathattan norm, the Taxicab norm

This is a sum of each of the absolute values and is denoted as

$L^1(v) = ||v||_1$

Where

$||v||_1 = |a_1|+ |a_2|...+|a_n|$


This comes into practice in several machine learning algorithms where the diffrence between an extremely small value and zero is needed. Also, useful for its mathematical simplicity

In [15]:
# L1 norm code

from numpy.linalg import norm

# to use the norm specify norm with the vecto as the first parmeter, and the numerical operator as the second
vector = np.array([2,4,6,8,10])

vectors_length_L1_norm = norm(vector,1)
print(f'The L1 norm is {vectors_length_L1_norm}')

The L1 norm is 30.0


## $L^2$ Norm


AKA Euclidean Norm, the most used in machine learning as a regulariztion method to keep coeffecients managable

This is a square rooted sum of each of the squares of the values.

The equation for calculating this is as follows


$L^2(v) = ||v||_2$


$||v||_2 = \sqrt{a_1^2 + a_2^2 + a_3^2...a_n^2}$

In [17]:
vectors_length_L2_norm = norm(vector,2)
print(f'The L2 norm is {vectors_length_L2_norm}')

The L2 norm is 14.832396974191326


## Vector Max Norm

This returns the maximum value of the vector in the array, this is used mostly in nueral networks, for max norm regularizaion

the equation is listed as:

$L^{inf}(v) =||v||_{inf} $

How this is calculated is

$||v||_{inf} = max{a_1,a_2,a_3}$

In [20]:
from math import inf
#to use the vector nor, drop the inf from tha math library and the vector into the norm function

vector_max_norm = norm(vector,inf)

print(f'The vector max norm is {vector_max_norm}')

The vector max norm is 10.0
